major release
cran-task-views/Tracking pull request #61
Opened 2023-06-20 10:40 UTC by rociojoo

2023-07-07 12:38 UTC, basille requested changes
I've finished the review. I cleaned all GitHub issues, added a few archived packages, and added a comment about actual check results… This needs to be addressed before merging.

2023-07-07 12:38 UTC, basille commented on NEWS.md
> +  not pass checks anymore
```suggestion
  not pass checks anymore
  * [`BayesianAnimalTracker`](https://github.com/cran-task-views/Tracking/issues/48): no
    longer on CRAN (archived on 2022-06-08)
  * [`BBMM`](https://github.com/cran-task-views/Tracking/issues/46): no
    longer on CRAN (archived on 2022-05-23)
```

2023-07-07 12:38 UTC, basille commented on NEWS.md
> +    longer on CRAN (archived on 2022-12-12).
```suggestion
    longer on CRAN (archived on 2022-12-12)
  * [`mkde`](https://github.com/cran-task-views/Tracking/issues/47): no
    longer on CRAN (archived on 2022-04-25).
```

2023-07-13 14:42 UTC, rociojoo commented on NEWS.md
> +4 packages have been removed from the list:
Thanks. Now they do.

2023-07-13 14:43 UTC, merged